CREATE TYPE taskStatus as ENUM('INCOMPLETE', 'PROCESSING', 'COMPLETED');

CREATE TABLE IF NOT EXISTS "Task" (
  id UUID PRIMARY KEY NOT NULL,
  "telegramId" VARCHAR(255) NOT NULL,
  "prompt" TEXT NOT NULL,
  "status" taskStatus NOT NULL DEFAULT 'INCOMPLETE',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
